# Generated by Django 3.1.5 on 2021-01-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier_code', models.CharField(max_length=20)),
                ('organization_unit_number', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person_firstname', models.CharField(max_length=50)),
                ('contact_person_lastname', models.CharField(max_length=50)),
                ('contact_person_phonenumber', models.CharField(max_length=50)),
                ('contact_person_email', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('postal_address', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(verbose_name='datetime created')),
                ('modified_datetime', models.DateTimeField(verbose_name='datetime modified')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_firstname', models.CharField(max_length=50)),
                ('contact_person_lastname', models.CharField(max_length=50)),
                ('contact_person_phonenumber', models.CharField(max_length=50)),
                ('contact_person_email', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('postal_address', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(verbose_name='datetime created')),
                ('modified_datetime', models.DateTimeField(verbose_name='datetime modified')),
            ],
        ),
    ]
